### ISSUE TITLE
unable to actuate number of people in a zone 

### ISSUE THREAD

**Issue by asrjy** [mechyai/RL-EmsPy#8]
Hi. I have been trying to simulate varying the number of people in a zone, but I keep getting the following error

> Exception ignored on calling ctypes callback function: <function EmsPy._enclosing_callback.<locals>._callback_function at 0x11cb99ee0>
> Traceback (most recent call last):
>   File "/Users/yash/Documents/Zodhya/RL-EmsPy/emspy/emspy.py", line 543, in _callback_function
>     self._set_ems_handles()
>   File "/Users/yash/Documents/Zodhya/RL-EmsPy/emspy/emspy.py", line 276, in _set_ems_handles
>     setattr(self, 'handle_' + ems_type + '_' + name, self._get_handle(ems_type, handle_inputs))
>   File "/Users/yash/Documents/Zodhya/RL-EmsPy/emspy/emspy.py", line 308, in _get_handle
>     raise Exception(f'ERROR: [{str(ems_obj_details)}]: The EMS sensor/actuator handle could not be '
> Exception: ERROR: [('People', 'Number of People', 'People_1')]: The EMS sensor/actuator handle could not be found. Please consult the .idf and/or your ToC for accuracy
> 

This is the People object in my IDF file

`
People,

  People_1,                               !- Name

  Ergo Office 1,                          !- Zone or ZoneList Name

  Ergo Schedule,                          !- Number of People Schedule Name

  People,                                 !- Number of People Calculation Method

  1,                                      !- Number of People

  ,                                       !- People per Zone Floor Area {person/m2}

  ,                                       !- Zone Floor Area per Person {m2/person}

  0.3,                                    !- Fraction Radiant

  ,                                       !- Sensible Heat Fraction

  Ergo Activity;                          !- Activity Level Schedule Name
`

And this is my tc_actuator dictionary

`
tc_actuators = {
    'zn0_people': ('People', 'Number of People', 'People_1'),  # deg C
}
`

**Comment by agl71** [comment]
Dear @asrjy
Do you have fixed the problem above?  Could tell me the detail?

Best Regards;
